spring:
#数据库连接配置
  datasource:
    username: root
    password: lucong
    url: jdbc:mysql://39.105.231.100:3306/one_code?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    #    host: 172.26.66.114
    host: 39.105.231.100
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: app_talk@123
    lettuce:
      pool:
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
      shutdown-timeout: 2000ms
    timeout: 5000ms

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oneCode.entity
  #开启驼峰
  configuration:
    map-underscore-to-camel-case: true
#mapper配置
mapper:
  mappers: com.oneCode.common.BaseMapper
  identity: MYSQL

#分页助手的配置
pagehelper:
  helperDialect: mysql
  reasonable: true  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql

#日志级别
logging:
  level:
    root: debug
    com.server.apptalk.mapper: debug
